### ISSUE TITLE
Improvement: priority for all participants

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#118]
When adding participants it would be great to be able to select priority for all of them, rather than 1 by 1 afterwards. This would also solve the problem of having a default priority of 1, which makes the experiment starts immediately for all of them.

**Comment by smathot** [comment]
Marking this as won't fix for now since it's a feature request rather than a bug fix.

**Comment by dschreij** [comment]
Let's leave it wontfix for now indeed. I understand this is a valuable addition, but it is a bit tricky to achieve and would require some time to implement.

**Comment by kristian-lange** [comment]
PR waiting https://github.com/open-cogsci/omm-server/pull/175
