### ISSUE TITLE
Statistics list of participants

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#119]
At present the statistics displayed on the participant’s list don’t tell us much because they display the % complete of a list of jobs that can be repeated, so it goes to 100% then fall back to 0. Is there a way to make it clearer so that it turns to completed when the experiment is really finished? Also, would it be possible to display the number of jobs done rather than the % complete? that would be very useful.

![participants_finished](https://user-images.githubusercontent.com/50901388/163540612-e7065003-353a-4a09-ba10-6e0c8bd16af0.PNG)

**Comment by smathot** [comment]
Marking this as won't fix for now since it's a feature request rather than a bug fix.

**Comment by kristian-lange** [comment]
@nclaidiere, @smathot, I exchanged the '% complete' with a '# results' (number of job results). Please have a look at the screenshot. Showing the percentage of finished jobs doesn't really make sense in my humble opinion because a single job can be done multiple times by a participant. What do you think?

![Image](https://github.com/user-attachments/assets/a6d8864d-e4dc-4491-9fb6-9d4f60922b5d)

**Comment by nclaidiere** [comment]
Yes Kristian, thanks! could you just change '# Results' by '# Trials'? thanks. A job becomes a certain set of conditions of an experiment, a trial is an instanciation of a job.

**Comment by kristian-lange** [comment]
Okay.

> A job becomes a certain set of conditions of an experiment, a trial is an instanciation of a job.
I was always wondering about the differences. Just for my understanding: form the database's point of view, a trail's data would be the job's data + the data produced by the experiment?

**Comment by nclaidiere** [comment]
Yes, I think ideally a trial is a combination of the experimantal conditions (defined by the job) and the results. The problem with the old database came from adding the experimental results to the job making it harder and harder to unpack and add experimental results to the job.

**Comment by kristian-lange** [comment]
@smathot Please feel free to merge if you are okay with the PR: https://github.com/open-cogsci/omm-server/pull/184
