### ISSUE TITLE
Activate/deactivate participants

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#121]
We have one monkey that died recently and I have realised that participants are then stuck in the list of participants and in experiments and I wonder if this can cause problems. For instance, what happens when we archive experiments? Can we then safely remove participants from the list without loosing data? Or is the participant stuck in an active state?

**Comment by dschreij** [comment]
There currently is no mechanism for this, but it could be added. There need to be changes throughout the application though to check for active status, so I expect this to be quite some work.

**Comment by smathot** [comment]
I've marked this as 'won't fix', for now as it's not really a bug but an additional feature that wasn't in the specs.

**Comment by dschreij** [comment]
I have just checked this and it actually is possible already to set participants to inactive:
![image](https://user-images.githubusercontent.com/689044/177480636-6ddd1a44-5d43-40da-98ba-59f5db2af4eb.png)
You can toggle the switch that you see at the bottom of the screenshot to change the status of a participant. Did you try that already, and if you did, how does this behave differently than you expect?

**Comment by nclaidiere** [comment]
Sorry I had not seen the option. I just tried it and I think that works just fine, the inactive participant is still part of the studies but cannot be identified again (i.e. fallback) and is no longer in the list of participants that can be assigned to experiments. Great!
