### ISSUE TITLE
Archived studies are still returned by announce 

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#132]
When a study is archived, it is still returned by the announce endpoint, whereas it should be ignored. This leads to a `NoJobsForParticipants` error in the client, which in turn results in the fallback experiment being selected. I suspect that this is what underlies a lot of the seemingly unpredictable behavior, such as described in #128.

**Comment by nclaidiere** [comment]
Oh great! That's a relief! I was really puzzled by the fact that everything went smoothly for a long time and then was completely messed up. But that fits with what I did and that also certainly explain why Pascal isn't having the same problems we have.

**Comment by dschreij** [comment]
Right. Probably a query that needs to be improved

**Comment by smathot** [comment]
Tested and fixed :+1:
