### ISSUE TITLE
Recent versions of docker compose don't work with docker-compose.yml

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#135]
After updating docker, the compose file no longer works. The culprit seems to be the `"${PORT}:${PORT}"` value in the server-ports section. I haven't been able to figure out how to resolve this, or what exactly changed in docker to suddenly break this. I'm using the latest version of Docker as of the time of writing, with docker engine v20.10.16.

```
C:\Users\Sebastiaan\Downloads>docker compose up -d
time="2022-07-05T08:58:14+02:00" level=warning msg="The \"PORT\" variable is not set. Defaulting to a blank string."
time="2022-07-05T08:58:14+02:00" level=warning msg="The \"PORT\" variable is not set. Defaulting to a blank string."
1 error(s) decoding:

* error decoding 'Ports': No port specified: :<empty>
```

Or when running `docker-compose` as one command:

```
C:\Users\Sebastiaan\Downloads>docker-compose up -d
WARNING: The PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.server.ports contains an invalid type, it should be a number, or an object
```

**Comment by dschreij** [comment]
I had the same thing when I did a clean install of this repo, and for me it turned out I forgot to copy the .env.example to an .env file. After I did that, everything runs fine on Docker 20.10.17. If that doesn't fix it for you, there may be another reason why docker compose isn't reading the env file.
