### ISSUE TITLE
Impossible to change ID of participant: network error

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#141]
Sebastiaan cleared the DB to start on a clean slate, so I had to create the participants anew. I made some mistakes when inputting the participant's IDs and now when I try to change it I receive the following error message. Everything else seems to be working properly and participants are not assigned to any experiments. This is problematic because from time to time we need to change the RFID of participants because they get broken. Is this an easy fix?

![network error](https://user-images.githubusercontent.com/50901388/195646531-e8f28e16-c39e-4152-a4f1-1c0c8f58e5ee.PNG)

**Comment by smathot** [comment]
I suspect that this is because of the URL your using to address the server, either localhost or 127.0.0.1 (forgot which). Using the wrong URL triggers a CORS error. Could that be it?

**Comment by nclaidiere** [comment]
Thanks, indeed, I was using the IP address (192.168.201.51) and when I switch to localhost I can change the ID. What is wrong with the IP address? cheers

**Comment by smathot** [comment]
The IP address that you use to address the server must be the same as the IP address that the server uses internally. Otherwise it seems as though data is being communicates from one computer to another and the browser blocks that for security reasons. So there's nothing wrong, it's just expected browser behavior.

**Comment by smathot** [comment]
There's no need to: the server is configured correctly as it is (I tested it, right?) and for the clients this issue doesn't matter! The issue only occurs in the server web interface, and only in particular situations when it calls itself.
