### ISSUE TITLE
Information left in the entry point announce plugin is not present in data

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#149]
Hi! I just realised that in the latest version of the server the information declared in the announce plugin is not present in the data. For instance, we use this field to record the 'computer number' using box: 31, the Box value was present in earlier versions but seem to have disappeared.

I am just putting below the way the data is entered in case that is the source of the problem, but I don't think so.

Cheers!

![image](https://user-images.githubusercontent.com/50901388/229451431-5471ce66-9913-464c-b6cc-1580a81ed21f.png)

**Comment by smathot** [comment]
Noted, I'll try to replicate it when I get a chance. Does this happen with every experiment?

**Comment by nclaidiere** [comment]
I just checked experiments from Nov 2022 and the field is missing, I suspect this happened during the last update and I did not notice until now.

**Comment by smathot** [comment]
I cannot reproduce the issue. Could it simply be that automatic logging of all variables is disabled, and that the `box` variable is not explicitly included in the `logger` item?

**Comment by nclaidiere** [comment]
Yes, automatic logging of all variables is disabled.

"that the box variable is not explicitly included in the logger item"
It is not, I thought the logger item was for variables in the experiment, not in the entry point... so each variable in the entry point needs to go into the logger item? That explains the problem.

Do you think it would be useful to make the entry point variables implicitly included in the logger?

**Comment by smathot** [comment]
> Do you think it would be useful to make the entry point variables implicitly included in the logger?

No ;-) The entry point variables are no different from the perspective of the experiment from any other experimental variable. They only have a different source. So if you use them, the same rules apply as for other variables: they are logged either if all variables are automatically logger or if they are explicitly marked for logging.

**Comment by nclaidiere** [comment]
Ok let's go with that.
