### ISSUE TITLE
Participants of a study should have a status indicating if they are first in line for this experiment.

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#16]
The second attentional-capture experiment from the screenshot below has been deleted (so not archived). This does effectively remove the study from the list of studies. Yet Panda still participates in it, and if I announce the Panda, it also returns this deleted experiment.

![image](https://user-images.githubusercontent.com/594936/98252933-c5352e00-1f7a-11eb-9b14-0bf42df2a9e3.png)

**Comment by dschreij** [comment]
Can this be closed with the current solution?

**Comment by smathot** [comment]
Yes!
