### ISSUE TITLE
Uploading experiment or job table results in `DOMException`

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#80]
When uploading an experiment file or job table, the upload never seems to finish and the following error message appears in the console. The upload does succeed though, but you need to refresh the page to see it.

![image](https://user-images.githubusercontent.com/594936/113173685-eeb46600-9249-11eb-8c3d-7d7d719282f3.png)

**Comment by dschreij** [comment]
I could reproduce this error. This was caused by a the dependency vue-fragment, which is broken at v1.5.2. I downgraded to v1.5.1 and this error no longer occurs

**Comment by dschreij** [comment]
I just released 0.5.4. Can you check if this fixes the issue for you too?

**Comment by smathot** [comment]
Fixed!
