### ISSUE TITLE
Increase the character limit for study descriptions

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#93]
Right now, study descriptions have a character limit of 1000. This should be increased considerably.

**Comment by dschreij** [comment]
What is the purpose in your view of this study description field? I intended it to be used for a short elaboration on what the study is about, if the title is not descriptive enough, and not to contain a long text of instructions on how the experiment should be run. I also designed the GUI for this field to be used in that way (e.g. the subtitle lines in the list items for studies on the study page, and by using a large font to show the description below the title on the study detail page). 

If you do intend to use this field for longer instruction texts, it may be a better idea to add an extra field to the study table and add this to the interface.

**Comment by nclaidiere** [comment]
"If you do intend to use this field for longer instruction texts, it may be a better idea to add an extra field to the study table and add this to the interface."
Yes, that's the idea, to be able to add comments on the study, maybe an event that happened during the experiment for instance... e.g. there was a covid pandemic that shut the lab for three months!

**Comment by dschreij** [comment]
Alright, so that sound more like you need some sort of logbook or even comments functionality. One big text field would also suffice though, but I would keep that separated from the study description (which serves other display purposes as well) and just add a new field or fields for this.

**Comment by dschreij** [comment]
I added an editable study info section and pushed this to the develop branch. It supports basic markdown for formatting as well (was really easy and out-of-the-box to add this). You'll find it as an extra tab on a study page. Please try it out.
One small note: studies that have been created before this field was added will show 'null' if the information field is empty, but newer studies do not. I don't think I need to find a solution that works around this problem.
